package one.transfinite.naac.teaching_plan;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;

import one.transfinite.naac.course.Course;
import one.transfinite.naac.department.Department;
import one.transfinite.naac.hod.Hod;
import one.transfinite.naac.program.FacultyProgram;
import one.transfinite.naac.program.FacultySeminar;
import one.transfinite.naac.program.Program;
import one.transfinite.naac.publication.BookPublication;
import one.transfinite.naac.publication.PaperPresented;
import one.transfinite.naac.publication.ResearchPublication;
import one.transfinite.naac.qualification.EntranceQualification;
import one.transfinite.naac.qualification.PGQualification;
import one.transfinite.naac.qualification.ResearchQualification;
import one.transfinite.naac.qualification.UGQualification;
import one.transfinite.naac.role.Role;
import one.transfinite.naac.role.RoleName;
import one.transfinite.naac.student.AdmittedStudent;
import one.transfinite.naac.student.Student;
import one.transfinite.naac.teacher.Teacher;
import one.transfinite.naac.teacher.TeacherAppointment;
import one.transfinite.naac.teacher.TeacherApproval;
import one.transfinite.naac.teacher.TeacherTransfer;
import one.transfinite.naac.user.User;
import org.junit.jupiter.api.Test;

class PHDRegisteredStudentTest {
    @Test
    void testConstructor() {
        PHDRegisteredStudent actualPhdRegisteredStudent = new PHDRegisteredStudent();
        actualPhdRegisteredStudent.setCertificate("Certificate");
        actualPhdRegisteredStudent.setId(123L);
        LocalDateTime atStartOfDayResult = LocalDate.of(1970, 1, 1).atStartOfDay();
        Date fromResult = Date.from(atStartOfDayResult.atZone(ZoneId.of("UTC")).toInstant());
        actualPhdRegisteredStudent.setRegistrationDate(fromResult);
        actualPhdRegisteredStudent.setResearchCentre("Research Centre");
        Department department = new Department();
        department.setId(123L);
        department.setDepartmentName("Department Name");
        department.setPrograms(new ArrayList<Program>());
        department.setEstablishmentYear("Establishment Year");
        Program program = new Program();
        program.setProgramCode("Program Code");
        program.setProgramName("Program Name");
        program.setCourses(new ArrayList<Course>());
        program.setProgramId(123L);
        program.setStartYear("Start Year");
        program.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program.setDepartment(department);
        program.setProgramType("Program Type");
        ResearchQualification researchQualification = new ResearchQualification();
        researchQualification.setSubject("Hello from the Dreaming Spires");
        researchQualification.setUniversity("University");
        researchQualification.setId(123L);
        researchQualification.setDegree("Degree");
        LocalDateTime atStartOfDayResult1 = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification.setDateOfDeclaration(Date.from(atStartOfDayResult1.atZone(ZoneId.of("UTC")).toInstant()));
        User user = new User();
        user.setLastName("Doe");
        user.setEmail("jane.doe@example.org");
        user.setPassword("iloveyou");
        user.setHod(new Hod());
        user.setRole(new Role());
        user.setUserId(123L);
        LocalDateTime atStartOfDayResult2 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setCreatedAt(Date.from(atStartOfDayResult2.atZone(ZoneId.of("UTC")).toInstant()));
        user.setMiddleName("Middle Name");
        user.setFirstName("Jane");
        LocalDateTime atStartOfDayResult3 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setDob(Date.from(atStartOfDayResult3.atZone(ZoneId.of("UTC")).toInstant()));
        user.setTeacher(new Teacher());
        user.setGender("Gender");
        user.setStudent(new Student());
        user.setPhone("4105551212");
        EntranceQualification entranceQualification = new EntranceQualification();
        entranceQualification.setSubject("Hello from the Dreaming Spires");
        entranceQualification.setUniversity("University");
        entranceQualification.setId(123L);
        entranceQualification.setName("Name");
        LocalDateTime atStartOfDayResult4 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification.setYearOfPassing(Date.from(atStartOfDayResult4.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification = new UGQualification();
        ugQualification.setDocument("Document");
        ugQualification.setUniversity("University");
        ugQualification.setSpecialization("Specialization");
        ugQualification.setId(123L);
        ugQualification.setDegree("Degree");
        ugQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult5 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification.setYearOfPassing(Date.from(atStartOfDayResult5.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification = new PGQualification();
        pgQualification.setDocument("Document");
        pgQualification.setUniversity("University");
        pgQualification.setSpecialization("Specialization");
        pgQualification.setId(123L);
        pgQualification.setDegree("Degree");
        pgQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult6 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification.setYearOfPassing(Date.from(atStartOfDayResult6.atZone(ZoneId.of("UTC")).toInstant()));
        Hod hod = new Hod();
        hod.setResearchQualification(researchQualification);
        hod.setUser(user);
        hod.setTeacherApprovals(new ArrayList<TeacherApproval>());
        hod.setEntranceQualification(entranceQualification);
        hod.setPanDocument("Pan Document");
        hod.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        hod.setBookPublications(new ArrayList<BookPublication>());
        hod.setResearchPublications(new ArrayList<ResearchPublication>());
        hod.setPaperPresentedList(new ArrayList<PaperPresented>());
        hod.setAadharDocument("Aadhar Document");
        hod.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        hod.setId(123L);
        hod.setUgQualification(ugQualification);
        hod.setPanNumber("42");
        hod.setAadharNumber("42");
        hod.setPgQualification(pgQualification);
        Role role = new Role();
        role.setRoleName(RoleName.Admin);
        role.setId(123L);
        ResearchQualification researchQualification1 = new ResearchQualification();
        researchQualification1.setSubject("Hello from the Dreaming Spires");
        researchQualification1.setUniversity("University");
        researchQualification1.setId(123L);
        researchQualification1.setDegree("Degree");
        LocalDateTime atStartOfDayResult7 = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification1.setDateOfDeclaration(Date.from(atStartOfDayResult7.atZone(ZoneId.of("UTC")).toInstant()));
        User user1 = new User();
        user1.setLastName("Doe");
        user1.setEmail("jane.doe@example.org");
        user1.setPassword("iloveyou");
        user1.setHod(new Hod());
        user1.setRole(new Role());
        user1.setUserId(123L);
        LocalDateTime atStartOfDayResult8 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setCreatedAt(Date.from(atStartOfDayResult8.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setMiddleName("Middle Name");
        user1.setFirstName("Jane");
        LocalDateTime atStartOfDayResult9 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setDob(Date.from(atStartOfDayResult9.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setTeacher(new Teacher());
        user1.setGender("Gender");
        user1.setStudent(new Student());
        user1.setPhone("4105551212");
        EntranceQualification entranceQualification1 = new EntranceQualification();
        entranceQualification1.setSubject("Hello from the Dreaming Spires");
        entranceQualification1.setUniversity("University");
        entranceQualification1.setId(123L);
        entranceQualification1.setName("Name");
        LocalDateTime atStartOfDayResult10 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification1.setYearOfPassing(Date.from(atStartOfDayResult10.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification1 = new UGQualification();
        ugQualification1.setDocument("Document");
        ugQualification1.setUniversity("University");
        ugQualification1.setSpecialization("Specialization");
        ugQualification1.setId(123L);
        ugQualification1.setDegree("Degree");
        ugQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult11 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification1.setYearOfPassing(Date.from(atStartOfDayResult11.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification1 = new PGQualification();
        pgQualification1.setDocument("Document");
        pgQualification1.setUniversity("University");
        pgQualification1.setSpecialization("Specialization");
        pgQualification1.setId(123L);
        pgQualification1.setDegree("Degree");
        pgQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult12 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification1.setYearOfPassing(Date.from(atStartOfDayResult12.atZone(ZoneId.of("UTC")).toInstant()));
        Teacher teacher = new Teacher();
        teacher.setResearchQualification(researchQualification1);
        teacher.setFacultyPrograms(new ArrayList<FacultyProgram>());
        teacher.setUser(user1);
        teacher.setTeacherApprovals(new ArrayList<TeacherApproval>());
        teacher.setEntranceQualification(entranceQualification1);
        teacher.setPanDocument("Pan Document");
        teacher.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        teacher.setBookPublications(new ArrayList<BookPublication>());
        teacher.setResearchPublications(new ArrayList<ResearchPublication>());
        teacher.setTeacherId(123L);
        teacher.setPaperPresentedList(new ArrayList<PaperPresented>());
        teacher.setAadharDocument("Aadhar Document");
        teacher.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        teacher.setUgQualification(ugQualification1);
        teacher.setPanNumber("42");
        teacher.setAadharNumber("42");
        teacher.setFacultySeminars(new ArrayList<FacultySeminar>());
        teacher.setPgQualification(pgQualification1);
        Program program1 = new Program();
        program1.setProgramCode("Program Code");
        program1.setProgramName("Program Name");
        program1.setCourses(new ArrayList<Course>());
        program1.setProgramId(123L);
        program1.setStartYear("Start Year");
        program1.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program1.setDepartment(new Department());
        program1.setProgramType("Program Type");
        User user2 = new User();
        user2.setLastName("Doe");
        user2.setEmail("jane.doe@example.org");
        user2.setPassword("iloveyou");
        user2.setHod(new Hod());
        user2.setRole(new Role());
        user2.setUserId(123L);
        LocalDateTime atStartOfDayResult13 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setCreatedAt(Date.from(atStartOfDayResult13.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setMiddleName("Middle Name");
        user2.setFirstName("Jane");
        LocalDateTime atStartOfDayResult14 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setDob(Date.from(atStartOfDayResult14.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setTeacher(new Teacher());
        user2.setGender("Gender");
        user2.setStudent(new Student());
        user2.setPhone("4105551212");
        Student student = new Student();
        student.setProgram(program1);
        student.setFatherName("Father Name");
        student.setReligion("Religion");
        student.setUser(user2);
        student.setPanDocument("Pan Document");
        student.setTenthMarks(10.0);
        student.setTwelthMarks(10.0);
        student.setStudentId(123L);
        student.setMotherName("Mother Name");
        student.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult15 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setStartDate(Date.from(atStartOfDayResult15.atZone(ZoneId.of("UTC")).toInstant()));
        student.setAadharDocument("Aadhar Document");
        student.setPanNumber("42");
        student.setAadharNumber("42");
        LocalDateTime atStartOfDayResult16 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setCompletionDate(Date.from(atStartOfDayResult16.atZone(ZoneId.of("UTC")).toInstant()));
        student.setMotherPhoneNumber("4105551212");
        student.setCast("Cast");
        User user3 = new User();
        user3.setLastName("Doe");
        user3.setEmail("jane.doe@example.org");
        user3.setPassword("iloveyou");
        user3.setHod(hod);
        user3.setRole(role);
        user3.setUserId(123L);
        LocalDateTime atStartOfDayResult17 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setCreatedAt(Date.from(atStartOfDayResult17.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setMiddleName("Middle Name");
        user3.setFirstName("Jane");
        LocalDateTime atStartOfDayResult18 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setDob(Date.from(atStartOfDayResult18.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setTeacher(teacher);
        user3.setGender("Gender");
        user3.setStudent(student);
        user3.setPhone("4105551212");
        Student student1 = new Student();
        student1.setProgram(program);
        student1.setFatherName("Father Name");
        student1.setReligion("Religion");
        student1.setUser(user3);
        student1.setPanDocument("Pan Document");
        student1.setTenthMarks(10.0);
        student1.setTwelthMarks(10.0);
        student1.setStudentId(123L);
        student1.setMotherName("Mother Name");
        student1.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult19 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setStartDate(Date.from(atStartOfDayResult19.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setAadharDocument("Aadhar Document");
        student1.setPanNumber("42");
        student1.setAadharNumber("42");
        LocalDateTime atStartOfDayResult20 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setCompletionDate(Date.from(atStartOfDayResult20.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setMotherPhoneNumber("4105551212");
        student1.setCast("Cast");
        actualPhdRegisteredStudent.setStudent(student1);
        actualPhdRegisteredStudent.setTitle("Dr");
        assertEquals("Certificate", actualPhdRegisteredStudent.getCertificate());
        assertEquals(123L, actualPhdRegisteredStudent.getId().longValue());
        assertSame(fromResult, actualPhdRegisteredStudent.getRegistrationDate());
        assertEquals("Research Centre", actualPhdRegisteredStudent.getResearchCentre());
        assertSame(student1, actualPhdRegisteredStudent.getStudent());
        assertEquals("Dr", actualPhdRegisteredStudent.getTitle());
    }

    @Test
    void testConstructor2() {
        Student student = new Student();
        PHDRegisteredStudent actualPhdRegisteredStudent = new PHDRegisteredStudent(123L, student, "Dr", new Date(1L),
                "Research Centre", "Certificate");
        actualPhdRegisteredStudent.setCertificate("Certificate");
        actualPhdRegisteredStudent.setId(123L);
        LocalDateTime atStartOfDayResult = LocalDate.of(1970, 1, 1).atStartOfDay();
        Date fromResult = Date.from(atStartOfDayResult.atZone(ZoneId.of("UTC")).toInstant());
        actualPhdRegisteredStudent.setRegistrationDate(fromResult);
        actualPhdRegisteredStudent.setResearchCentre("Research Centre");
        Department department = new Department();
        department.setId(123L);
        department.setDepartmentName("Department Name");
        department.setPrograms(new ArrayList<Program>());
        department.setEstablishmentYear("Establishment Year");
        Program program = new Program();
        program.setProgramCode("Program Code");
        program.setProgramName("Program Name");
        program.setCourses(new ArrayList<Course>());
        program.setProgramId(123L);
        program.setStartYear("Start Year");
        program.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program.setDepartment(department);
        program.setProgramType("Program Type");
        ResearchQualification researchQualification = new ResearchQualification();
        researchQualification.setSubject("Hello from the Dreaming Spires");
        researchQualification.setUniversity("University");
        researchQualification.setId(123L);
        researchQualification.setDegree("Degree");
        LocalDateTime atStartOfDayResult1 = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification.setDateOfDeclaration(Date.from(atStartOfDayResult1.atZone(ZoneId.of("UTC")).toInstant()));
        User user = new User();
        user.setLastName("Doe");
        user.setEmail("jane.doe@example.org");
        user.setPassword("iloveyou");
        user.setHod(new Hod());
        user.setRole(new Role());
        user.setUserId(123L);
        LocalDateTime atStartOfDayResult2 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setCreatedAt(Date.from(atStartOfDayResult2.atZone(ZoneId.of("UTC")).toInstant()));
        user.setMiddleName("Middle Name");
        user.setFirstName("Jane");
        LocalDateTime atStartOfDayResult3 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setDob(Date.from(atStartOfDayResult3.atZone(ZoneId.of("UTC")).toInstant()));
        user.setTeacher(new Teacher());
        user.setGender("Gender");
        user.setStudent(new Student());
        user.setPhone("4105551212");
        EntranceQualification entranceQualification = new EntranceQualification();
        entranceQualification.setSubject("Hello from the Dreaming Spires");
        entranceQualification.setUniversity("University");
        entranceQualification.setId(123L);
        entranceQualification.setName("Name");
        LocalDateTime atStartOfDayResult4 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification.setYearOfPassing(Date.from(atStartOfDayResult4.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification = new UGQualification();
        ugQualification.setDocument("Document");
        ugQualification.setUniversity("University");
        ugQualification.setSpecialization("Specialization");
        ugQualification.setId(123L);
        ugQualification.setDegree("Degree");
        ugQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult5 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification.setYearOfPassing(Date.from(atStartOfDayResult5.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification = new PGQualification();
        pgQualification.setDocument("Document");
        pgQualification.setUniversity("University");
        pgQualification.setSpecialization("Specialization");
        pgQualification.setId(123L);
        pgQualification.setDegree("Degree");
        pgQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult6 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification.setYearOfPassing(Date.from(atStartOfDayResult6.atZone(ZoneId.of("UTC")).toInstant()));
        Hod hod = new Hod();
        hod.setResearchQualification(researchQualification);
        hod.setUser(user);
        hod.setTeacherApprovals(new ArrayList<TeacherApproval>());
        hod.setEntranceQualification(entranceQualification);
        hod.setPanDocument("Pan Document");
        hod.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        hod.setBookPublications(new ArrayList<BookPublication>());
        hod.setResearchPublications(new ArrayList<ResearchPublication>());
        hod.setPaperPresentedList(new ArrayList<PaperPresented>());
        hod.setAadharDocument("Aadhar Document");
        hod.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        hod.setId(123L);
        hod.setUgQualification(ugQualification);
        hod.setPanNumber("42");
        hod.setAadharNumber("42");
        hod.setPgQualification(pgQualification);
        Role role = new Role();
        role.setRoleName(RoleName.Admin);
        role.setId(123L);
        ResearchQualification researchQualification1 = new ResearchQualification();
        researchQualification1.setSubject("Hello from the Dreaming Spires");
        researchQualification1.setUniversity("University");
        researchQualification1.setId(123L);
        researchQualification1.setDegree("Degree");
        LocalDateTime atStartOfDayResult7 = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification1.setDateOfDeclaration(Date.from(atStartOfDayResult7.atZone(ZoneId.of("UTC")).toInstant()));
        User user1 = new User();
        user1.setLastName("Doe");
        user1.setEmail("jane.doe@example.org");
        user1.setPassword("iloveyou");
        user1.setHod(new Hod());
        user1.setRole(new Role());
        user1.setUserId(123L);
        LocalDateTime atStartOfDayResult8 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setCreatedAt(Date.from(atStartOfDayResult8.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setMiddleName("Middle Name");
        user1.setFirstName("Jane");
        LocalDateTime atStartOfDayResult9 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setDob(Date.from(atStartOfDayResult9.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setTeacher(new Teacher());
        user1.setGender("Gender");
        user1.setStudent(new Student());
        user1.setPhone("4105551212");
        EntranceQualification entranceQualification1 = new EntranceQualification();
        entranceQualification1.setSubject("Hello from the Dreaming Spires");
        entranceQualification1.setUniversity("University");
        entranceQualification1.setId(123L);
        entranceQualification1.setName("Name");
        LocalDateTime atStartOfDayResult10 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification1.setYearOfPassing(Date.from(atStartOfDayResult10.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification1 = new UGQualification();
        ugQualification1.setDocument("Document");
        ugQualification1.setUniversity("University");
        ugQualification1.setSpecialization("Specialization");
        ugQualification1.setId(123L);
        ugQualification1.setDegree("Degree");
        ugQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult11 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification1.setYearOfPassing(Date.from(atStartOfDayResult11.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification1 = new PGQualification();
        pgQualification1.setDocument("Document");
        pgQualification1.setUniversity("University");
        pgQualification1.setSpecialization("Specialization");
        pgQualification1.setId(123L);
        pgQualification1.setDegree("Degree");
        pgQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult12 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification1.setYearOfPassing(Date.from(atStartOfDayResult12.atZone(ZoneId.of("UTC")).toInstant()));
        Teacher teacher = new Teacher();
        teacher.setResearchQualification(researchQualification1);
        teacher.setFacultyPrograms(new ArrayList<FacultyProgram>());
        teacher.setUser(user1);
        teacher.setTeacherApprovals(new ArrayList<TeacherApproval>());
        teacher.setEntranceQualification(entranceQualification1);
        teacher.setPanDocument("Pan Document");
        teacher.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        teacher.setBookPublications(new ArrayList<BookPublication>());
        teacher.setResearchPublications(new ArrayList<ResearchPublication>());
        teacher.setTeacherId(123L);
        teacher.setPaperPresentedList(new ArrayList<PaperPresented>());
        teacher.setAadharDocument("Aadhar Document");
        teacher.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        teacher.setUgQualification(ugQualification1);
        teacher.setPanNumber("42");
        teacher.setAadharNumber("42");
        teacher.setFacultySeminars(new ArrayList<FacultySeminar>());
        teacher.setPgQualification(pgQualification1);
        Program program1 = new Program();
        program1.setProgramCode("Program Code");
        program1.setProgramName("Program Name");
        program1.setCourses(new ArrayList<Course>());
        program1.setProgramId(123L);
        program1.setStartYear("Start Year");
        program1.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program1.setDepartment(new Department());
        program1.setProgramType("Program Type");
        User user2 = new User();
        user2.setLastName("Doe");
        user2.setEmail("jane.doe@example.org");
        user2.setPassword("iloveyou");
        user2.setHod(new Hod());
        user2.setRole(new Role());
        user2.setUserId(123L);
        LocalDateTime atStartOfDayResult13 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setCreatedAt(Date.from(atStartOfDayResult13.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setMiddleName("Middle Name");
        user2.setFirstName("Jane");
        LocalDateTime atStartOfDayResult14 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setDob(Date.from(atStartOfDayResult14.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setTeacher(new Teacher());
        user2.setGender("Gender");
        user2.setStudent(new Student());
        user2.setPhone("4105551212");
        Student student1 = new Student();
        student1.setProgram(program1);
        student1.setFatherName("Father Name");
        student1.setReligion("Religion");
        student1.setUser(user2);
        student1.setPanDocument("Pan Document");
        student1.setTenthMarks(10.0);
        student1.setTwelthMarks(10.0);
        student1.setStudentId(123L);
        student1.setMotherName("Mother Name");
        student1.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult15 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setStartDate(Date.from(atStartOfDayResult15.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setAadharDocument("Aadhar Document");
        student1.setPanNumber("42");
        student1.setAadharNumber("42");
        LocalDateTime atStartOfDayResult16 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setCompletionDate(Date.from(atStartOfDayResult16.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setMotherPhoneNumber("4105551212");
        student1.setCast("Cast");
        User user3 = new User();
        user3.setLastName("Doe");
        user3.setEmail("jane.doe@example.org");
        user3.setPassword("iloveyou");
        user3.setHod(hod);
        user3.setRole(role);
        user3.setUserId(123L);
        LocalDateTime atStartOfDayResult17 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setCreatedAt(Date.from(atStartOfDayResult17.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setMiddleName("Middle Name");
        user3.setFirstName("Jane");
        LocalDateTime atStartOfDayResult18 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setDob(Date.from(atStartOfDayResult18.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setTeacher(teacher);
        user3.setGender("Gender");
        user3.setStudent(student1);
        user3.setPhone("4105551212");
        Student student2 = new Student();
        student2.setProgram(program);
        student2.setFatherName("Father Name");
        student2.setReligion("Religion");
        student2.setUser(user3);
        student2.setPanDocument("Pan Document");
        student2.setTenthMarks(10.0);
        student2.setTwelthMarks(10.0);
        student2.setStudentId(123L);
        student2.setMotherName("Mother Name");
        student2.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult19 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setStartDate(Date.from(atStartOfDayResult19.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setAadharDocument("Aadhar Document");
        student2.setPanNumber("42");
        student2.setAadharNumber("42");
        LocalDateTime atStartOfDayResult20 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setCompletionDate(Date.from(atStartOfDayResult20.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setMotherPhoneNumber("4105551212");
        student2.setCast("Cast");
        actualPhdRegisteredStudent.setStudent(student2);
        actualPhdRegisteredStudent.setTitle("Dr");
        assertEquals("Certificate", actualPhdRegisteredStudent.getCertificate());
        assertEquals(123L, actualPhdRegisteredStudent.getId().longValue());
        assertSame(fromResult, actualPhdRegisteredStudent.getRegistrationDate());
        assertEquals("Research Centre", actualPhdRegisteredStudent.getResearchCentre());
        assertSame(student2, actualPhdRegisteredStudent.getStudent());
        assertEquals("Dr", actualPhdRegisteredStudent.getTitle());
    }
}

