package one.transfinite.naac.teaching_plan;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;

import one.transfinite.naac.course.Course;
import one.transfinite.naac.department.Department;
import one.transfinite.naac.hod.Hod;
import one.transfinite.naac.program.FacultyProgram;
import one.transfinite.naac.program.FacultySeminar;
import one.transfinite.naac.program.Program;
import one.transfinite.naac.publication.BookPublication;
import one.transfinite.naac.publication.PaperPresented;
import one.transfinite.naac.publication.ResearchPublication;
import one.transfinite.naac.qualification.EntranceQualification;
import one.transfinite.naac.qualification.PGQualification;
import one.transfinite.naac.qualification.ResearchQualification;
import one.transfinite.naac.qualification.UGQualification;
import one.transfinite.naac.role.Role;
import one.transfinite.naac.role.RoleName;
import one.transfinite.naac.student.AdmittedStudent;
import one.transfinite.naac.student.Student;
import one.transfinite.naac.teacher.Teacher;
import one.transfinite.naac.teacher.TeacherAppointment;
import one.transfinite.naac.teacher.TeacherApproval;
import one.transfinite.naac.teacher.TeacherTransfer;
import one.transfinite.naac.user.User;
import org.junit.jupiter.api.Test;

class ResearchStudentTest {
    @Test
    void testConstructor() {
        ResearchStudent actualResearchStudent = new ResearchStudent();
        actualResearchStudent.setAcademicYear("Academic Year");
        actualResearchStudent.setId(123L);
        Department department = new Department();
        department.setId(123L);
        department.setDepartmentName("Department Name");
        department.setPrograms(new ArrayList<Program>());
        department.setEstablishmentYear("Establishment Year");
        Program program = new Program();
        program.setProgramCode("Program Code");
        program.setProgramName("Program Name");
        program.setCourses(new ArrayList<Course>());
        program.setProgramId(123L);
        program.setStartYear("Start Year");
        program.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program.setDepartment(department);
        program.setProgramType("Program Type");
        Hod hod = new Hod();
        hod.setResearchQualification(new ResearchQualification());
        hod.setUser(new User());
        hod.setTeacherApprovals(new ArrayList<TeacherApproval>());
        hod.setEntranceQualification(new EntranceQualification());
        hod.setPanDocument("Pan Document");
        hod.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        hod.setBookPublications(new ArrayList<BookPublication>());
        hod.setResearchPublications(new ArrayList<ResearchPublication>());
        hod.setPaperPresentedList(new ArrayList<PaperPresented>());
        hod.setAadharDocument("Aadhar Document");
        hod.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        hod.setId(123L);
        hod.setUgQualification(new UGQualification());
        hod.setPanNumber("42");
        hod.setAadharNumber("42");
        hod.setPgQualification(new PGQualification());
        Role role = new Role();
        role.setRoleName(RoleName.Admin);
        role.setId(123L);
        Teacher teacher = new Teacher();
        teacher.setResearchQualification(new ResearchQualification());
        teacher.setFacultyPrograms(new ArrayList<FacultyProgram>());
        teacher.setUser(new User());
        teacher.setTeacherApprovals(new ArrayList<TeacherApproval>());
        teacher.setEntranceQualification(new EntranceQualification());
        teacher.setPanDocument("Pan Document");
        teacher.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        teacher.setBookPublications(new ArrayList<BookPublication>());
        teacher.setResearchPublications(new ArrayList<ResearchPublication>());
        teacher.setTeacherId(123L);
        teacher.setPaperPresentedList(new ArrayList<PaperPresented>());
        teacher.setAadharDocument("Aadhar Document");
        teacher.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        teacher.setUgQualification(new UGQualification());
        teacher.setPanNumber("42");
        teacher.setAadharNumber("42");
        teacher.setFacultySeminars(new ArrayList<FacultySeminar>());
        teacher.setPgQualification(new PGQualification());
        Student student = new Student();
        student.setProgram(new Program());
        student.setFatherName("Father Name");
        student.setReligion("Religion");
        student.setUser(new User());
        student.setPanDocument("Pan Document");
        student.setTenthMarks(10.0);
        student.setTwelthMarks(10.0);
        student.setStudentId(123L);
        student.setMotherName("Mother Name");
        student.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setStartDate(Date.from(atStartOfDayResult.atZone(ZoneId.of("UTC")).toInstant()));
        student.setAadharDocument("Aadhar Document");
        student.setPanNumber("42");
        student.setAadharNumber("42");
        LocalDateTime atStartOfDayResult1 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setCompletionDate(Date.from(atStartOfDayResult1.atZone(ZoneId.of("UTC")).toInstant()));
        student.setMotherPhoneNumber("4105551212");
        student.setCast("Cast");
        User user = new User();
        user.setLastName("Doe");
        user.setEmail("jane.doe@example.org");
        user.setPassword("iloveyou");
        user.setHod(hod);
        user.setRole(role);
        user.setUserId(123L);
        LocalDateTime atStartOfDayResult2 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setCreatedAt(Date.from(atStartOfDayResult2.atZone(ZoneId.of("UTC")).toInstant()));
        user.setMiddleName("Middle Name");
        user.setFirstName("Jane");
        LocalDateTime atStartOfDayResult3 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setDob(Date.from(atStartOfDayResult3.atZone(ZoneId.of("UTC")).toInstant()));
        user.setTeacher(teacher);
        user.setGender("Gender");
        user.setStudent(student);
        user.setPhone("4105551212");
        Student student1 = new Student();
        student1.setProgram(program);
        student1.setFatherName("Father Name");
        student1.setReligion("Religion");
        student1.setUser(user);
        student1.setPanDocument("Pan Document");
        student1.setTenthMarks(10.0);
        student1.setTwelthMarks(10.0);
        student1.setStudentId(123L);
        student1.setMotherName("Mother Name");
        student1.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult4 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setStartDate(Date.from(atStartOfDayResult4.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setAadharDocument("Aadhar Document");
        student1.setPanNumber("42");
        student1.setAadharNumber("42");
        LocalDateTime atStartOfDayResult5 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setCompletionDate(Date.from(atStartOfDayResult5.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setMotherPhoneNumber("4105551212");
        student1.setCast("Cast");
        PHDDeclaration phdDeclaration = new PHDDeclaration();
        LocalDateTime atStartOfDayResult6 = LocalDate.of(1970, 1, 1).atStartOfDay();
        phdDeclaration.setRegistrationDate(Date.from(atStartOfDayResult6.atZone(ZoneId.of("UTC")).toInstant()));
        phdDeclaration.setCertificate("Certificate");
        phdDeclaration.setId(123L);
        phdDeclaration.setResearchCentre("Research Centre");
        phdDeclaration.setStudent(student1);
        LocalDateTime atStartOfDayResult7 = LocalDate.of(1970, 1, 1).atStartOfDay();
        phdDeclaration.setDateOfDeclaration(Date.from(atStartOfDayResult7.atZone(ZoneId.of("UTC")).toInstant()));
        phdDeclaration.setTitle("Dr");
        actualResearchStudent.setPhdDeclaration(phdDeclaration);
        Department department1 = new Department();
        department1.setId(123L);
        department1.setDepartmentName("Department Name");
        department1.setPrograms(new ArrayList<Program>());
        department1.setEstablishmentYear("Establishment Year");
        Program program1 = new Program();
        program1.setProgramCode("Program Code");
        program1.setProgramName("Program Name");
        program1.setCourses(new ArrayList<Course>());
        program1.setProgramId(123L);
        program1.setStartYear("Start Year");
        program1.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program1.setDepartment(department1);
        program1.setProgramType("Program Type");
        Hod hod1 = new Hod();
        hod1.setResearchQualification(new ResearchQualification());
        hod1.setUser(new User());
        hod1.setTeacherApprovals(new ArrayList<TeacherApproval>());
        hod1.setEntranceQualification(new EntranceQualification());
        hod1.setPanDocument("Pan Document");
        hod1.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        hod1.setBookPublications(new ArrayList<BookPublication>());
        hod1.setResearchPublications(new ArrayList<ResearchPublication>());
        hod1.setPaperPresentedList(new ArrayList<PaperPresented>());
        hod1.setAadharDocument("Aadhar Document");
        hod1.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        hod1.setId(123L);
        hod1.setUgQualification(new UGQualification());
        hod1.setPanNumber("42");
        hod1.setAadharNumber("42");
        hod1.setPgQualification(new PGQualification());
        Role role1 = new Role();
        role1.setRoleName(RoleName.Admin);
        role1.setId(123L);
        Teacher teacher1 = new Teacher();
        teacher1.setResearchQualification(new ResearchQualification());
        teacher1.setFacultyPrograms(new ArrayList<FacultyProgram>());
        teacher1.setUser(new User());
        teacher1.setTeacherApprovals(new ArrayList<TeacherApproval>());
        teacher1.setEntranceQualification(new EntranceQualification());
        teacher1.setPanDocument("Pan Document");
        teacher1.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        teacher1.setBookPublications(new ArrayList<BookPublication>());
        teacher1.setResearchPublications(new ArrayList<ResearchPublication>());
        teacher1.setTeacherId(123L);
        teacher1.setPaperPresentedList(new ArrayList<PaperPresented>());
        teacher1.setAadharDocument("Aadhar Document");
        teacher1.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        teacher1.setUgQualification(new UGQualification());
        teacher1.setPanNumber("42");
        teacher1.setAadharNumber("42");
        teacher1.setFacultySeminars(new ArrayList<FacultySeminar>());
        teacher1.setPgQualification(new PGQualification());
        Student student2 = new Student();
        student2.setProgram(new Program());
        student2.setFatherName("Father Name");
        student2.setReligion("Religion");
        student2.setUser(new User());
        student2.setPanDocument("Pan Document");
        student2.setTenthMarks(10.0);
        student2.setTwelthMarks(10.0);
        student2.setStudentId(123L);
        student2.setMotherName("Mother Name");
        student2.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult8 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setStartDate(Date.from(atStartOfDayResult8.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setAadharDocument("Aadhar Document");
        student2.setPanNumber("42");
        student2.setAadharNumber("42");
        LocalDateTime atStartOfDayResult9 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setCompletionDate(Date.from(atStartOfDayResult9.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setMotherPhoneNumber("4105551212");
        student2.setCast("Cast");
        User user1 = new User();
        user1.setLastName("Doe");
        user1.setEmail("jane.doe@example.org");
        user1.setPassword("iloveyou");
        user1.setHod(hod1);
        user1.setRole(role1);
        user1.setUserId(123L);
        LocalDateTime atStartOfDayResult10 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setCreatedAt(Date.from(atStartOfDayResult10.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setMiddleName("Middle Name");
        user1.setFirstName("Jane");
        LocalDateTime atStartOfDayResult11 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setDob(Date.from(atStartOfDayResult11.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setTeacher(teacher1);
        user1.setGender("Gender");
        user1.setStudent(student2);
        user1.setPhone("4105551212");
        Student student3 = new Student();
        student3.setProgram(program1);
        student3.setFatherName("Father Name");
        student3.setReligion("Religion");
        student3.setUser(user1);
        student3.setPanDocument("Pan Document");
        student3.setTenthMarks(10.0);
        student3.setTwelthMarks(10.0);
        student3.setStudentId(123L);
        student3.setMotherName("Mother Name");
        student3.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult12 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student3.setStartDate(Date.from(atStartOfDayResult12.atZone(ZoneId.of("UTC")).toInstant()));
        student3.setAadharDocument("Aadhar Document");
        student3.setPanNumber("42");
        student3.setAadharNumber("42");
        LocalDateTime atStartOfDayResult13 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student3.setCompletionDate(Date.from(atStartOfDayResult13.atZone(ZoneId.of("UTC")).toInstant()));
        student3.setMotherPhoneNumber("4105551212");
        student3.setCast("Cast");
        PHDRegisteredStudent phdRegisteredStudent = new PHDRegisteredStudent();
        LocalDateTime atStartOfDayResult14 = LocalDate.of(1970, 1, 1).atStartOfDay();
        phdRegisteredStudent.setRegistrationDate(Date.from(atStartOfDayResult14.atZone(ZoneId.of("UTC")).toInstant()));
        phdRegisteredStudent.setCertificate("Certificate");
        phdRegisteredStudent.setId(123L);
        phdRegisteredStudent.setResearchCentre("Research Centre");
        phdRegisteredStudent.setStudent(student3);
        phdRegisteredStudent.setTitle("Dr");
        actualResearchStudent.setPhdRegisteredStudent(phdRegisteredStudent);
        assertEquals("Academic Year", actualResearchStudent.getAcademicYear());
        assertEquals(123L, actualResearchStudent.getId().longValue());
        assertSame(phdDeclaration, actualResearchStudent.getPhdDeclaration());
        assertSame(phdRegisteredStudent, actualResearchStudent.getPhdRegisteredStudent());
    }

    @Test
    void testConstructor2() {
        PHDRegisteredStudent phdRegisteredStudent = new PHDRegisteredStudent();
        ResearchStudent actualResearchStudent = new ResearchStudent(123L, "Academic Year", phdRegisteredStudent,
                new PHDDeclaration());
        actualResearchStudent.setAcademicYear("Academic Year");
        actualResearchStudent.setId(123L);
        Department department = new Department();
        department.setId(123L);
        department.setDepartmentName("Department Name");
        department.setPrograms(new ArrayList<Program>());
        department.setEstablishmentYear("Establishment Year");
        Program program = new Program();
        program.setProgramCode("Program Code");
        program.setProgramName("Program Name");
        program.setCourses(new ArrayList<Course>());
        program.setProgramId(123L);
        program.setStartYear("Start Year");
        program.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program.setDepartment(department);
        program.setProgramType("Program Type");
        Hod hod = new Hod();
        hod.setResearchQualification(new ResearchQualification());
        hod.setUser(new User());
        hod.setTeacherApprovals(new ArrayList<TeacherApproval>());
        hod.setEntranceQualification(new EntranceQualification());
        hod.setPanDocument("Pan Document");
        hod.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        hod.setBookPublications(new ArrayList<BookPublication>());
        hod.setResearchPublications(new ArrayList<ResearchPublication>());
        hod.setPaperPresentedList(new ArrayList<PaperPresented>());
        hod.setAadharDocument("Aadhar Document");
        hod.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        hod.setId(123L);
        hod.setUgQualification(new UGQualification());
        hod.setPanNumber("42");
        hod.setAadharNumber("42");
        hod.setPgQualification(new PGQualification());
        Role role = new Role();
        role.setRoleName(RoleName.Admin);
        role.setId(123L);
        Teacher teacher = new Teacher();
        teacher.setResearchQualification(new ResearchQualification());
        teacher.setFacultyPrograms(new ArrayList<FacultyProgram>());
        teacher.setUser(new User());
        teacher.setTeacherApprovals(new ArrayList<TeacherApproval>());
        teacher.setEntranceQualification(new EntranceQualification());
        teacher.setPanDocument("Pan Document");
        teacher.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        teacher.setBookPublications(new ArrayList<BookPublication>());
        teacher.setResearchPublications(new ArrayList<ResearchPublication>());
        teacher.setTeacherId(123L);
        teacher.setPaperPresentedList(new ArrayList<PaperPresented>());
        teacher.setAadharDocument("Aadhar Document");
        teacher.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        teacher.setUgQualification(new UGQualification());
        teacher.setPanNumber("42");
        teacher.setAadharNumber("42");
        teacher.setFacultySeminars(new ArrayList<FacultySeminar>());
        teacher.setPgQualification(new PGQualification());
        Student student = new Student();
        student.setProgram(new Program());
        student.setFatherName("Father Name");
        student.setReligion("Religion");
        student.setUser(new User());
        student.setPanDocument("Pan Document");
        student.setTenthMarks(10.0);
        student.setTwelthMarks(10.0);
        student.setStudentId(123L);
        student.setMotherName("Mother Name");
        student.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setStartDate(Date.from(atStartOfDayResult.atZone(ZoneId.of("UTC")).toInstant()));
        student.setAadharDocument("Aadhar Document");
        student.setPanNumber("42");
        student.setAadharNumber("42");
        LocalDateTime atStartOfDayResult1 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setCompletionDate(Date.from(atStartOfDayResult1.atZone(ZoneId.of("UTC")).toInstant()));
        student.setMotherPhoneNumber("4105551212");
        student.setCast("Cast");
        User user = new User();
        user.setLastName("Doe");
        user.setEmail("jane.doe@example.org");
        user.setPassword("iloveyou");
        user.setHod(hod);
        user.setRole(role);
        user.setUserId(123L);
        LocalDateTime atStartOfDayResult2 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setCreatedAt(Date.from(atStartOfDayResult2.atZone(ZoneId.of("UTC")).toInstant()));
        user.setMiddleName("Middle Name");
        user.setFirstName("Jane");
        LocalDateTime atStartOfDayResult3 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setDob(Date.from(atStartOfDayResult3.atZone(ZoneId.of("UTC")).toInstant()));
        user.setTeacher(teacher);
        user.setGender("Gender");
        user.setStudent(student);
        user.setPhone("4105551212");
        Student student1 = new Student();
        student1.setProgram(program);
        student1.setFatherName("Father Name");
        student1.setReligion("Religion");
        student1.setUser(user);
        student1.setPanDocument("Pan Document");
        student1.setTenthMarks(10.0);
        student1.setTwelthMarks(10.0);
        student1.setStudentId(123L);
        student1.setMotherName("Mother Name");
        student1.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult4 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setStartDate(Date.from(atStartOfDayResult4.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setAadharDocument("Aadhar Document");
        student1.setPanNumber("42");
        student1.setAadharNumber("42");
        LocalDateTime atStartOfDayResult5 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setCompletionDate(Date.from(atStartOfDayResult5.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setMotherPhoneNumber("4105551212");
        student1.setCast("Cast");
        PHDDeclaration phdDeclaration = new PHDDeclaration();
        LocalDateTime atStartOfDayResult6 = LocalDate.of(1970, 1, 1).atStartOfDay();
        phdDeclaration.setRegistrationDate(Date.from(atStartOfDayResult6.atZone(ZoneId.of("UTC")).toInstant()));
        phdDeclaration.setCertificate("Certificate");
        phdDeclaration.setId(123L);
        phdDeclaration.setResearchCentre("Research Centre");
        phdDeclaration.setStudent(student1);
        LocalDateTime atStartOfDayResult7 = LocalDate.of(1970, 1, 1).atStartOfDay();
        phdDeclaration.setDateOfDeclaration(Date.from(atStartOfDayResult7.atZone(ZoneId.of("UTC")).toInstant()));
        phdDeclaration.setTitle("Dr");
        actualResearchStudent.setPhdDeclaration(phdDeclaration);
        Department department1 = new Department();
        department1.setId(123L);
        department1.setDepartmentName("Department Name");
        department1.setPrograms(new ArrayList<Program>());
        department1.setEstablishmentYear("Establishment Year");
        Program program1 = new Program();
        program1.setProgramCode("Program Code");
        program1.setProgramName("Program Name");
        program1.setCourses(new ArrayList<Course>());
        program1.setProgramId(123L);
        program1.setStartYear("Start Year");
        program1.setAdmittedStudents(new ArrayList<AdmittedStudent>());
        program1.setDepartment(department1);
        program1.setProgramType("Program Type");
        Hod hod1 = new Hod();
        hod1.setResearchQualification(new ResearchQualification());
        hod1.setUser(new User());
        hod1.setTeacherApprovals(new ArrayList<TeacherApproval>());
        hod1.setEntranceQualification(new EntranceQualification());
        hod1.setPanDocument("Pan Document");
        hod1.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        hod1.setBookPublications(new ArrayList<BookPublication>());
        hod1.setResearchPublications(new ArrayList<ResearchPublication>());
        hod1.setPaperPresentedList(new ArrayList<PaperPresented>());
        hod1.setAadharDocument("Aadhar Document");
        hod1.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        hod1.setId(123L);
        hod1.setUgQualification(new UGQualification());
        hod1.setPanNumber("42");
        hod1.setAadharNumber("42");
        hod1.setPgQualification(new PGQualification());
        Role role1 = new Role();
        role1.setRoleName(RoleName.Admin);
        role1.setId(123L);
        Teacher teacher1 = new Teacher();
        teacher1.setResearchQualification(new ResearchQualification());
        teacher1.setFacultyPrograms(new ArrayList<FacultyProgram>());
        teacher1.setUser(new User());
        teacher1.setTeacherApprovals(new ArrayList<TeacherApproval>());
        teacher1.setEntranceQualification(new EntranceQualification());
        teacher1.setPanDocument("Pan Document");
        teacher1.setTeacherTransfers(new ArrayList<TeacherTransfer>());
        teacher1.setBookPublications(new ArrayList<BookPublication>());
        teacher1.setResearchPublications(new ArrayList<ResearchPublication>());
        teacher1.setTeacherId(123L);
        teacher1.setPaperPresentedList(new ArrayList<PaperPresented>());
        teacher1.setAadharDocument("Aadhar Document");
        teacher1.setTeacherAppointments(new ArrayList<TeacherAppointment>());
        teacher1.setUgQualification(new UGQualification());
        teacher1.setPanNumber("42");
        teacher1.setAadharNumber("42");
        teacher1.setFacultySeminars(new ArrayList<FacultySeminar>());
        teacher1.setPgQualification(new PGQualification());
        Student student2 = new Student();
        student2.setProgram(new Program());
        student2.setFatherName("Father Name");
        student2.setReligion("Religion");
        student2.setUser(new User());
        student2.setPanDocument("Pan Document");
        student2.setTenthMarks(10.0);
        student2.setTwelthMarks(10.0);
        student2.setStudentId(123L);
        student2.setMotherName("Mother Name");
        student2.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult8 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setStartDate(Date.from(atStartOfDayResult8.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setAadharDocument("Aadhar Document");
        student2.setPanNumber("42");
        student2.setAadharNumber("42");
        LocalDateTime atStartOfDayResult9 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setCompletionDate(Date.from(atStartOfDayResult9.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setMotherPhoneNumber("4105551212");
        student2.setCast("Cast");
        User user1 = new User();
        user1.setLastName("Doe");
        user1.setEmail("jane.doe@example.org");
        user1.setPassword("iloveyou");
        user1.setHod(hod1);
        user1.setRole(role1);
        user1.setUserId(123L);
        LocalDateTime atStartOfDayResult10 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setCreatedAt(Date.from(atStartOfDayResult10.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setMiddleName("Middle Name");
        user1.setFirstName("Jane");
        LocalDateTime atStartOfDayResult11 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setDob(Date.from(atStartOfDayResult11.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setTeacher(teacher1);
        user1.setGender("Gender");
        user1.setStudent(student2);
        user1.setPhone("4105551212");
        Student student3 = new Student();
        student3.setProgram(program1);
        student3.setFatherName("Father Name");
        student3.setReligion("Religion");
        student3.setUser(user1);
        student3.setPanDocument("Pan Document");
        student3.setTenthMarks(10.0);
        student3.setTwelthMarks(10.0);
        student3.setStudentId(123L);
        student3.setMotherName("Mother Name");
        student3.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult12 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student3.setStartDate(Date.from(atStartOfDayResult12.atZone(ZoneId.of("UTC")).toInstant()));
        student3.setAadharDocument("Aadhar Document");
        student3.setPanNumber("42");
        student3.setAadharNumber("42");
        LocalDateTime atStartOfDayResult13 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student3.setCompletionDate(Date.from(atStartOfDayResult13.atZone(ZoneId.of("UTC")).toInstant()));
        student3.setMotherPhoneNumber("4105551212");
        student3.setCast("Cast");
        PHDRegisteredStudent phdRegisteredStudent1 = new PHDRegisteredStudent();
        LocalDateTime atStartOfDayResult14 = LocalDate.of(1970, 1, 1).atStartOfDay();
        phdRegisteredStudent1.setRegistrationDate(Date.from(atStartOfDayResult14.atZone(ZoneId.of("UTC")).toInstant()));
        phdRegisteredStudent1.setCertificate("Certificate");
        phdRegisteredStudent1.setId(123L);
        phdRegisteredStudent1.setResearchCentre("Research Centre");
        phdRegisteredStudent1.setStudent(student3);
        phdRegisteredStudent1.setTitle("Dr");
        actualResearchStudent.setPhdRegisteredStudent(phdRegisteredStudent1);
        assertEquals("Academic Year", actualResearchStudent.getAcademicYear());
        assertEquals(123L, actualResearchStudent.getId().longValue());
        assertSame(phdDeclaration, actualResearchStudent.getPhdDeclaration());
        assertSame(phdRegisteredStudent1, actualResearchStudent.getPhdRegisteredStudent());
    }
}

