package one.transfinite.naac.teaching_plan;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import one.transfinite.naac.course.Course;
import one.transfinite.naac.department.Department;
import one.transfinite.naac.hod.Hod;
import one.transfinite.naac.program.FacultyProgram;
import one.transfinite.naac.program.FacultySeminar;
import one.transfinite.naac.program.Program;
import one.transfinite.naac.publication.BookPublication;
import one.transfinite.naac.publication.PaperPresented;
import one.transfinite.naac.publication.ResearchPublication;
import one.transfinite.naac.qualification.EntranceQualification;
import one.transfinite.naac.qualification.PGQualification;
import one.transfinite.naac.qualification.ResearchQualification;
import one.transfinite.naac.qualification.UGQualification;
import one.transfinite.naac.role.Role;
import one.transfinite.naac.role.RoleName;
import one.transfinite.naac.student.AdmittedStudent;
import one.transfinite.naac.student.Student;
import one.transfinite.naac.teacher.Teacher;
import one.transfinite.naac.teacher.TeacherAppointment;
import one.transfinite.naac.teacher.TeacherApproval;
import one.transfinite.naac.teacher.TeacherTransfer;
import one.transfinite.naac.user.User;
import org.junit.jupiter.api.Test;

class StudentCourseMappingTest {
    @Test
    void testConstructor() {
        StudentCourseMapping actualStudentCourseMapping = new StudentCourseMapping();
        ArrayList<AllottedMark> allottedMarkList = new ArrayList<AllottedMark>();
        actualStudentCourseMapping.setAllottedMarks(allottedMarkList);
        actualStudentCourseMapping.setId(123L);
        Department department = new Department();
        department.setId(123L);
        department.setDepartmentName("Department Name");
        ArrayList<Program> programList = new ArrayList<Program>();
        department.setPrograms(programList);
        department.setEstablishmentYear("Establishment Year");
        Program program = new Program();
        program.setProgramCode("Program Code");
        program.setProgramName("Program Name");
        ArrayList<Course> courseList = new ArrayList<Course>();
        program.setCourses(courseList);
        program.setProgramId(123L);
        program.setStartYear("Start Year");
        ArrayList<AdmittedStudent> admittedStudentList = new ArrayList<AdmittedStudent>();
        program.setAdmittedStudents(admittedStudentList);
        program.setDepartment(department);
        program.setProgramType("Program Type");
        ResearchQualification researchQualification = new ResearchQualification();
        researchQualification.setSubject("Hello from the Dreaming Spires");
        researchQualification.setUniversity("University");
        researchQualification.setId(123L);
        researchQualification.setDegree("Degree");
        LocalDateTime atStartOfDayResult = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification.setDateOfDeclaration(Date.from(atStartOfDayResult.atZone(ZoneId.of("UTC")).toInstant()));
        User user = new User();
        user.setLastName("Doe");
        user.setEmail("jane.doe@example.org");
        user.setPassword("iloveyou");
        user.setHod(new Hod());
        user.setRole(new Role());
        user.setUserId(123L);
        LocalDateTime atStartOfDayResult1 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setCreatedAt(Date.from(atStartOfDayResult1.atZone(ZoneId.of("UTC")).toInstant()));
        user.setMiddleName("Middle Name");
        user.setFirstName("Jane");
        LocalDateTime atStartOfDayResult2 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setDob(Date.from(atStartOfDayResult2.atZone(ZoneId.of("UTC")).toInstant()));
        user.setTeacher(new Teacher());
        user.setGender("Gender");
        user.setStudent(new Student());
        user.setPhone("4105551212");
        EntranceQualification entranceQualification = new EntranceQualification();
        entranceQualification.setSubject("Hello from the Dreaming Spires");
        entranceQualification.setUniversity("University");
        entranceQualification.setId(123L);
        entranceQualification.setName("Name");
        LocalDateTime atStartOfDayResult3 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification.setYearOfPassing(Date.from(atStartOfDayResult3.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification = new UGQualification();
        ugQualification.setDocument("Document");
        ugQualification.setUniversity("University");
        ugQualification.setSpecialization("Specialization");
        ugQualification.setId(123L);
        ugQualification.setDegree("Degree");
        ugQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult4 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification.setYearOfPassing(Date.from(atStartOfDayResult4.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification = new PGQualification();
        pgQualification.setDocument("Document");
        pgQualification.setUniversity("University");
        pgQualification.setSpecialization("Specialization");
        pgQualification.setId(123L);
        pgQualification.setDegree("Degree");
        pgQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult5 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification.setYearOfPassing(Date.from(atStartOfDayResult5.atZone(ZoneId.of("UTC")).toInstant()));
        Hod hod = new Hod();
        hod.setResearchQualification(researchQualification);
        hod.setUser(user);
        ArrayList<TeacherApproval> teacherApprovalList = new ArrayList<TeacherApproval>();
        hod.setTeacherApprovals(teacherApprovalList);
        hod.setEntranceQualification(entranceQualification);
        hod.setPanDocument("Pan Document");
        ArrayList<TeacherTransfer> teacherTransferList = new ArrayList<TeacherTransfer>();
        hod.setTeacherTransfers(teacherTransferList);
        ArrayList<BookPublication> bookPublicationList = new ArrayList<BookPublication>();
        hod.setBookPublications(bookPublicationList);
        ArrayList<ResearchPublication> researchPublicationList = new ArrayList<ResearchPublication>();
        hod.setResearchPublications(researchPublicationList);
        ArrayList<PaperPresented> paperPresentedList = new ArrayList<PaperPresented>();
        hod.setPaperPresentedList(paperPresentedList);
        hod.setAadharDocument("Aadhar Document");
        ArrayList<TeacherAppointment> teacherAppointmentList = new ArrayList<TeacherAppointment>();
        hod.setTeacherAppointments(teacherAppointmentList);
        hod.setId(123L);
        hod.setUgQualification(ugQualification);
        hod.setPanNumber("42");
        hod.setAadharNumber("42");
        hod.setPgQualification(pgQualification);
        Role role = new Role();
        role.setRoleName(RoleName.Admin);
        role.setId(123L);
        ResearchQualification researchQualification1 = new ResearchQualification();
        researchQualification1.setSubject("Hello from the Dreaming Spires");
        researchQualification1.setUniversity("University");
        researchQualification1.setId(123L);
        researchQualification1.setDegree("Degree");
        LocalDateTime atStartOfDayResult6 = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification1.setDateOfDeclaration(Date.from(atStartOfDayResult6.atZone(ZoneId.of("UTC")).toInstant()));
        User user1 = new User();
        user1.setLastName("Doe");
        user1.setEmail("jane.doe@example.org");
        user1.setPassword("iloveyou");
        user1.setHod(new Hod());
        user1.setRole(new Role());
        user1.setUserId(123L);
        LocalDateTime atStartOfDayResult7 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setCreatedAt(Date.from(atStartOfDayResult7.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setMiddleName("Middle Name");
        user1.setFirstName("Jane");
        LocalDateTime atStartOfDayResult8 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setDob(Date.from(atStartOfDayResult8.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setTeacher(new Teacher());
        user1.setGender("Gender");
        user1.setStudent(new Student());
        user1.setPhone("4105551212");
        EntranceQualification entranceQualification1 = new EntranceQualification();
        entranceQualification1.setSubject("Hello from the Dreaming Spires");
        entranceQualification1.setUniversity("University");
        entranceQualification1.setId(123L);
        entranceQualification1.setName("Name");
        LocalDateTime atStartOfDayResult9 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification1.setYearOfPassing(Date.from(atStartOfDayResult9.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification1 = new UGQualification();
        ugQualification1.setDocument("Document");
        ugQualification1.setUniversity("University");
        ugQualification1.setSpecialization("Specialization");
        ugQualification1.setId(123L);
        ugQualification1.setDegree("Degree");
        ugQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult10 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification1.setYearOfPassing(Date.from(atStartOfDayResult10.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification1 = new PGQualification();
        pgQualification1.setDocument("Document");
        pgQualification1.setUniversity("University");
        pgQualification1.setSpecialization("Specialization");
        pgQualification1.setId(123L);
        pgQualification1.setDegree("Degree");
        pgQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult11 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification1.setYearOfPassing(Date.from(atStartOfDayResult11.atZone(ZoneId.of("UTC")).toInstant()));
        Teacher teacher = new Teacher();
        teacher.setResearchQualification(researchQualification1);
        ArrayList<FacultyProgram> facultyProgramList = new ArrayList<FacultyProgram>();
        teacher.setFacultyPrograms(facultyProgramList);
        teacher.setUser(user1);
        ArrayList<TeacherApproval> teacherApprovalList1 = new ArrayList<TeacherApproval>();
        teacher.setTeacherApprovals(teacherApprovalList1);
        teacher.setEntranceQualification(entranceQualification1);
        teacher.setPanDocument("Pan Document");
        ArrayList<TeacherTransfer> teacherTransferList1 = new ArrayList<TeacherTransfer>();
        teacher.setTeacherTransfers(teacherTransferList1);
        ArrayList<BookPublication> bookPublicationList1 = new ArrayList<BookPublication>();
        teacher.setBookPublications(bookPublicationList1);
        ArrayList<ResearchPublication> researchPublicationList1 = new ArrayList<ResearchPublication>();
        teacher.setResearchPublications(researchPublicationList1);
        teacher.setTeacherId(123L);
        ArrayList<PaperPresented> paperPresentedList1 = new ArrayList<PaperPresented>();
        teacher.setPaperPresentedList(paperPresentedList1);
        teacher.setAadharDocument("Aadhar Document");
        ArrayList<TeacherAppointment> teacherAppointmentList1 = new ArrayList<TeacherAppointment>();
        teacher.setTeacherAppointments(teacherAppointmentList1);
        teacher.setUgQualification(ugQualification1);
        teacher.setPanNumber("42");
        teacher.setAadharNumber("42");
        ArrayList<FacultySeminar> facultySeminarList = new ArrayList<FacultySeminar>();
        teacher.setFacultySeminars(facultySeminarList);
        teacher.setPgQualification(pgQualification1);
        Program program1 = new Program();
        program1.setProgramCode("Program Code");
        program1.setProgramName("Program Name");
        ArrayList<Course> courseList1 = new ArrayList<Course>();
        program1.setCourses(courseList1);
        program1.setProgramId(123L);
        program1.setStartYear("Start Year");
        ArrayList<AdmittedStudent> admittedStudentList1 = new ArrayList<AdmittedStudent>();
        program1.setAdmittedStudents(admittedStudentList1);
        program1.setDepartment(new Department());
        program1.setProgramType("Program Type");
        User user2 = new User();
        user2.setLastName("Doe");
        user2.setEmail("jane.doe@example.org");
        user2.setPassword("iloveyou");
        user2.setHod(new Hod());
        user2.setRole(new Role());
        user2.setUserId(123L);
        LocalDateTime atStartOfDayResult12 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setCreatedAt(Date.from(atStartOfDayResult12.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setMiddleName("Middle Name");
        user2.setFirstName("Jane");
        LocalDateTime atStartOfDayResult13 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setDob(Date.from(atStartOfDayResult13.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setTeacher(new Teacher());
        user2.setGender("Gender");
        user2.setStudent(new Student());
        user2.setPhone("4105551212");
        Student student = new Student();
        student.setProgram(program1);
        student.setFatherName("Father Name");
        student.setReligion("Religion");
        student.setUser(user2);
        student.setPanDocument("Pan Document");
        student.setTenthMarks(10.0);
        student.setTwelthMarks(10.0);
        student.setStudentId(123L);
        student.setMotherName("Mother Name");
        student.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult14 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setStartDate(Date.from(atStartOfDayResult14.atZone(ZoneId.of("UTC")).toInstant()));
        student.setAadharDocument("Aadhar Document");
        student.setPanNumber("42");
        student.setAadharNumber("42");
        LocalDateTime atStartOfDayResult15 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student.setCompletionDate(Date.from(atStartOfDayResult15.atZone(ZoneId.of("UTC")).toInstant()));
        student.setMotherPhoneNumber("4105551212");
        student.setCast("Cast");
        User user3 = new User();
        user3.setLastName("Doe");
        user3.setEmail("jane.doe@example.org");
        user3.setPassword("iloveyou");
        user3.setHod(hod);
        user3.setRole(role);
        user3.setUserId(123L);
        LocalDateTime atStartOfDayResult16 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setCreatedAt(Date.from(atStartOfDayResult16.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setMiddleName("Middle Name");
        user3.setFirstName("Jane");
        LocalDateTime atStartOfDayResult17 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setDob(Date.from(atStartOfDayResult17.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setTeacher(teacher);
        user3.setGender("Gender");
        user3.setStudent(student);
        user3.setPhone("4105551212");
        Student student1 = new Student();
        student1.setProgram(program);
        student1.setFatherName("Father Name");
        student1.setReligion("Religion");
        student1.setUser(user3);
        student1.setPanDocument("Pan Document");
        student1.setTenthMarks(10.0);
        student1.setTwelthMarks(10.0);
        student1.setStudentId(123L);
        student1.setMotherName("Mother Name");
        student1.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult18 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setStartDate(Date.from(atStartOfDayResult18.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setAadharDocument("Aadhar Document");
        student1.setPanNumber("42");
        student1.setAadharNumber("42");
        LocalDateTime atStartOfDayResult19 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setCompletionDate(Date.from(atStartOfDayResult19.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setMotherPhoneNumber("4105551212");
        student1.setCast("Cast");
        actualStudentCourseMapping.setStudent(student1);
        List<AllottedMark> allottedMarks = actualStudentCourseMapping.getAllottedMarks();
        assertSame(allottedMarkList, allottedMarks);
        assertEquals(courseList, allottedMarks);
        assertEquals(admittedStudentList, allottedMarks);
        assertEquals(programList, allottedMarks);
        assertEquals(teacherApprovalList, allottedMarks);
        assertEquals(teacherTransferList, allottedMarks);
        assertEquals(bookPublicationList, allottedMarks);
        assertEquals(researchPublicationList, allottedMarks);
        assertEquals(paperPresentedList, allottedMarks);
        assertEquals(teacherAppointmentList, allottedMarks);
        assertEquals(facultyProgramList, allottedMarks);
        assertEquals(teacherApprovalList1, allottedMarks);
        assertEquals(teacherTransferList1, allottedMarks);
        assertEquals(bookPublicationList1, allottedMarks);
        assertEquals(researchPublicationList1, allottedMarks);
        assertEquals(paperPresentedList1, allottedMarks);
        assertEquals(teacherAppointmentList1, allottedMarks);
        assertEquals(facultySeminarList, allottedMarks);
        assertEquals(courseList1, allottedMarks);
        assertEquals(admittedStudentList1, allottedMarks);
        assertEquals(123L, actualStudentCourseMapping.getId().longValue());
        assertSame(student1, actualStudentCourseMapping.getStudent());
    }

    @Test
    void testConstructor2() {
        Student student = new Student();
        ArrayList<AllottedMark> allottedMarkList = new ArrayList<AllottedMark>();
        StudentCourseMapping actualStudentCourseMapping = new StudentCourseMapping(123L, student, allottedMarkList);
        ArrayList<AllottedMark> allottedMarkList1 = new ArrayList<AllottedMark>();
        actualStudentCourseMapping.setAllottedMarks(allottedMarkList1);
        actualStudentCourseMapping.setId(123L);
        Department department = new Department();
        department.setId(123L);
        department.setDepartmentName("Department Name");
        ArrayList<Program> programList = new ArrayList<Program>();
        department.setPrograms(programList);
        department.setEstablishmentYear("Establishment Year");
        Program program = new Program();
        program.setProgramCode("Program Code");
        program.setProgramName("Program Name");
        ArrayList<Course> courseList = new ArrayList<Course>();
        program.setCourses(courseList);
        program.setProgramId(123L);
        program.setStartYear("Start Year");
        ArrayList<AdmittedStudent> admittedStudentList = new ArrayList<AdmittedStudent>();
        program.setAdmittedStudents(admittedStudentList);
        program.setDepartment(department);
        program.setProgramType("Program Type");
        ResearchQualification researchQualification = new ResearchQualification();
        researchQualification.setSubject("Hello from the Dreaming Spires");
        researchQualification.setUniversity("University");
        researchQualification.setId(123L);
        researchQualification.setDegree("Degree");
        LocalDateTime atStartOfDayResult = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification.setDateOfDeclaration(Date.from(atStartOfDayResult.atZone(ZoneId.of("UTC")).toInstant()));
        User user = new User();
        user.setLastName("Doe");
        user.setEmail("jane.doe@example.org");
        user.setPassword("iloveyou");
        user.setHod(new Hod());
        user.setRole(new Role());
        user.setUserId(123L);
        LocalDateTime atStartOfDayResult1 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setCreatedAt(Date.from(atStartOfDayResult1.atZone(ZoneId.of("UTC")).toInstant()));
        user.setMiddleName("Middle Name");
        user.setFirstName("Jane");
        LocalDateTime atStartOfDayResult2 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user.setDob(Date.from(atStartOfDayResult2.atZone(ZoneId.of("UTC")).toInstant()));
        user.setTeacher(new Teacher());
        user.setGender("Gender");
        user.setStudent(new Student());
        user.setPhone("4105551212");
        EntranceQualification entranceQualification = new EntranceQualification();
        entranceQualification.setSubject("Hello from the Dreaming Spires");
        entranceQualification.setUniversity("University");
        entranceQualification.setId(123L);
        entranceQualification.setName("Name");
        LocalDateTime atStartOfDayResult3 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification.setYearOfPassing(Date.from(atStartOfDayResult3.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification = new UGQualification();
        ugQualification.setDocument("Document");
        ugQualification.setUniversity("University");
        ugQualification.setSpecialization("Specialization");
        ugQualification.setId(123L);
        ugQualification.setDegree("Degree");
        ugQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult4 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification.setYearOfPassing(Date.from(atStartOfDayResult4.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification = new PGQualification();
        pgQualification.setDocument("Document");
        pgQualification.setUniversity("University");
        pgQualification.setSpecialization("Specialization");
        pgQualification.setId(123L);
        pgQualification.setDegree("Degree");
        pgQualification.setGrade("Grade");
        LocalDateTime atStartOfDayResult5 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification.setYearOfPassing(Date.from(atStartOfDayResult5.atZone(ZoneId.of("UTC")).toInstant()));
        Hod hod = new Hod();
        hod.setResearchQualification(researchQualification);
        hod.setUser(user);
        ArrayList<TeacherApproval> teacherApprovalList = new ArrayList<TeacherApproval>();
        hod.setTeacherApprovals(teacherApprovalList);
        hod.setEntranceQualification(entranceQualification);
        hod.setPanDocument("Pan Document");
        ArrayList<TeacherTransfer> teacherTransferList = new ArrayList<TeacherTransfer>();
        hod.setTeacherTransfers(teacherTransferList);
        ArrayList<BookPublication> bookPublicationList = new ArrayList<BookPublication>();
        hod.setBookPublications(bookPublicationList);
        ArrayList<ResearchPublication> researchPublicationList = new ArrayList<ResearchPublication>();
        hod.setResearchPublications(researchPublicationList);
        ArrayList<PaperPresented> paperPresentedList = new ArrayList<PaperPresented>();
        hod.setPaperPresentedList(paperPresentedList);
        hod.setAadharDocument("Aadhar Document");
        ArrayList<TeacherAppointment> teacherAppointmentList = new ArrayList<TeacherAppointment>();
        hod.setTeacherAppointments(teacherAppointmentList);
        hod.setId(123L);
        hod.setUgQualification(ugQualification);
        hod.setPanNumber("42");
        hod.setAadharNumber("42");
        hod.setPgQualification(pgQualification);
        Role role = new Role();
        role.setRoleName(RoleName.Admin);
        role.setId(123L);
        ResearchQualification researchQualification1 = new ResearchQualification();
        researchQualification1.setSubject("Hello from the Dreaming Spires");
        researchQualification1.setUniversity("University");
        researchQualification1.setId(123L);
        researchQualification1.setDegree("Degree");
        LocalDateTime atStartOfDayResult6 = LocalDate.of(1970, 1, 1).atStartOfDay();
        researchQualification1.setDateOfDeclaration(Date.from(atStartOfDayResult6.atZone(ZoneId.of("UTC")).toInstant()));
        User user1 = new User();
        user1.setLastName("Doe");
        user1.setEmail("jane.doe@example.org");
        user1.setPassword("iloveyou");
        user1.setHod(new Hod());
        user1.setRole(new Role());
        user1.setUserId(123L);
        LocalDateTime atStartOfDayResult7 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setCreatedAt(Date.from(atStartOfDayResult7.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setMiddleName("Middle Name");
        user1.setFirstName("Jane");
        LocalDateTime atStartOfDayResult8 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user1.setDob(Date.from(atStartOfDayResult8.atZone(ZoneId.of("UTC")).toInstant()));
        user1.setTeacher(new Teacher());
        user1.setGender("Gender");
        user1.setStudent(new Student());
        user1.setPhone("4105551212");
        EntranceQualification entranceQualification1 = new EntranceQualification();
        entranceQualification1.setSubject("Hello from the Dreaming Spires");
        entranceQualification1.setUniversity("University");
        entranceQualification1.setId(123L);
        entranceQualification1.setName("Name");
        LocalDateTime atStartOfDayResult9 = LocalDate.of(1970, 1, 1).atStartOfDay();
        entranceQualification1.setYearOfPassing(Date.from(atStartOfDayResult9.atZone(ZoneId.of("UTC")).toInstant()));
        UGQualification ugQualification1 = new UGQualification();
        ugQualification1.setDocument("Document");
        ugQualification1.setUniversity("University");
        ugQualification1.setSpecialization("Specialization");
        ugQualification1.setId(123L);
        ugQualification1.setDegree("Degree");
        ugQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult10 = LocalDate.of(1970, 1, 1).atStartOfDay();
        ugQualification1.setYearOfPassing(Date.from(atStartOfDayResult10.atZone(ZoneId.of("UTC")).toInstant()));
        PGQualification pgQualification1 = new PGQualification();
        pgQualification1.setDocument("Document");
        pgQualification1.setUniversity("University");
        pgQualification1.setSpecialization("Specialization");
        pgQualification1.setId(123L);
        pgQualification1.setDegree("Degree");
        pgQualification1.setGrade("Grade");
        LocalDateTime atStartOfDayResult11 = LocalDate.of(1970, 1, 1).atStartOfDay();
        pgQualification1.setYearOfPassing(Date.from(atStartOfDayResult11.atZone(ZoneId.of("UTC")).toInstant()));
        Teacher teacher = new Teacher();
        teacher.setResearchQualification(researchQualification1);
        ArrayList<FacultyProgram> facultyProgramList = new ArrayList<FacultyProgram>();
        teacher.setFacultyPrograms(facultyProgramList);
        teacher.setUser(user1);
        ArrayList<TeacherApproval> teacherApprovalList1 = new ArrayList<TeacherApproval>();
        teacher.setTeacherApprovals(teacherApprovalList1);
        teacher.setEntranceQualification(entranceQualification1);
        teacher.setPanDocument("Pan Document");
        ArrayList<TeacherTransfer> teacherTransferList1 = new ArrayList<TeacherTransfer>();
        teacher.setTeacherTransfers(teacherTransferList1);
        ArrayList<BookPublication> bookPublicationList1 = new ArrayList<BookPublication>();
        teacher.setBookPublications(bookPublicationList1);
        ArrayList<ResearchPublication> researchPublicationList1 = new ArrayList<ResearchPublication>();
        teacher.setResearchPublications(researchPublicationList1);
        teacher.setTeacherId(123L);
        ArrayList<PaperPresented> paperPresentedList1 = new ArrayList<PaperPresented>();
        teacher.setPaperPresentedList(paperPresentedList1);
        teacher.setAadharDocument("Aadhar Document");
        ArrayList<TeacherAppointment> teacherAppointmentList1 = new ArrayList<TeacherAppointment>();
        teacher.setTeacherAppointments(teacherAppointmentList1);
        teacher.setUgQualification(ugQualification1);
        teacher.setPanNumber("42");
        teacher.setAadharNumber("42");
        ArrayList<FacultySeminar> facultySeminarList = new ArrayList<FacultySeminar>();
        teacher.setFacultySeminars(facultySeminarList);
        teacher.setPgQualification(pgQualification1);
        Program program1 = new Program();
        program1.setProgramCode("Program Code");
        program1.setProgramName("Program Name");
        ArrayList<Course> courseList1 = new ArrayList<Course>();
        program1.setCourses(courseList1);
        program1.setProgramId(123L);
        program1.setStartYear("Start Year");
        ArrayList<AdmittedStudent> admittedStudentList1 = new ArrayList<AdmittedStudent>();
        program1.setAdmittedStudents(admittedStudentList1);
        program1.setDepartment(new Department());
        program1.setProgramType("Program Type");
        User user2 = new User();
        user2.setLastName("Doe");
        user2.setEmail("jane.doe@example.org");
        user2.setPassword("iloveyou");
        user2.setHod(new Hod());
        user2.setRole(new Role());
        user2.setUserId(123L);
        LocalDateTime atStartOfDayResult12 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setCreatedAt(Date.from(atStartOfDayResult12.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setMiddleName("Middle Name");
        user2.setFirstName("Jane");
        LocalDateTime atStartOfDayResult13 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user2.setDob(Date.from(atStartOfDayResult13.atZone(ZoneId.of("UTC")).toInstant()));
        user2.setTeacher(new Teacher());
        user2.setGender("Gender");
        user2.setStudent(new Student());
        user2.setPhone("4105551212");
        Student student1 = new Student();
        student1.setProgram(program1);
        student1.setFatherName("Father Name");
        student1.setReligion("Religion");
        student1.setUser(user2);
        student1.setPanDocument("Pan Document");
        student1.setTenthMarks(10.0);
        student1.setTwelthMarks(10.0);
        student1.setStudentId(123L);
        student1.setMotherName("Mother Name");
        student1.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult14 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setStartDate(Date.from(atStartOfDayResult14.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setAadharDocument("Aadhar Document");
        student1.setPanNumber("42");
        student1.setAadharNumber("42");
        LocalDateTime atStartOfDayResult15 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student1.setCompletionDate(Date.from(atStartOfDayResult15.atZone(ZoneId.of("UTC")).toInstant()));
        student1.setMotherPhoneNumber("4105551212");
        student1.setCast("Cast");
        User user3 = new User();
        user3.setLastName("Doe");
        user3.setEmail("jane.doe@example.org");
        user3.setPassword("iloveyou");
        user3.setHod(hod);
        user3.setRole(role);
        user3.setUserId(123L);
        LocalDateTime atStartOfDayResult16 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setCreatedAt(Date.from(atStartOfDayResult16.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setMiddleName("Middle Name");
        user3.setFirstName("Jane");
        LocalDateTime atStartOfDayResult17 = LocalDate.of(1970, 1, 1).atStartOfDay();
        user3.setDob(Date.from(atStartOfDayResult17.atZone(ZoneId.of("UTC")).toInstant()));
        user3.setTeacher(teacher);
        user3.setGender("Gender");
        user3.setStudent(student1);
        user3.setPhone("4105551212");
        Student student2 = new Student();
        student2.setProgram(program);
        student2.setFatherName("Father Name");
        student2.setReligion("Religion");
        student2.setUser(user3);
        student2.setPanDocument("Pan Document");
        student2.setTenthMarks(10.0);
        student2.setTwelthMarks(10.0);
        student2.setStudentId(123L);
        student2.setMotherName("Mother Name");
        student2.setFatherPhoneNumber("4105551212");
        LocalDateTime atStartOfDayResult18 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setStartDate(Date.from(atStartOfDayResult18.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setAadharDocument("Aadhar Document");
        student2.setPanNumber("42");
        student2.setAadharNumber("42");
        LocalDateTime atStartOfDayResult19 = LocalDate.of(1970, 1, 1).atStartOfDay();
        student2.setCompletionDate(Date.from(atStartOfDayResult19.atZone(ZoneId.of("UTC")).toInstant()));
        student2.setMotherPhoneNumber("4105551212");
        student2.setCast("Cast");
        actualStudentCourseMapping.setStudent(student2);
        List<AllottedMark> allottedMarks = actualStudentCourseMapping.getAllottedMarks();
        assertSame(allottedMarkList1, allottedMarks);
        assertEquals(allottedMarkList, allottedMarks);
        assertEquals(courseList, allottedMarks);
        assertEquals(admittedStudentList, allottedMarks);
        assertEquals(programList, allottedMarks);
        assertEquals(teacherApprovalList, allottedMarks);
        assertEquals(teacherTransferList, allottedMarks);
        assertEquals(bookPublicationList, allottedMarks);
        assertEquals(researchPublicationList, allottedMarks);
        assertEquals(paperPresentedList, allottedMarks);
        assertEquals(teacherAppointmentList, allottedMarks);
        assertEquals(facultyProgramList, allottedMarks);
        assertEquals(teacherApprovalList1, allottedMarks);
        assertEquals(teacherTransferList1, allottedMarks);
        assertEquals(bookPublicationList1, allottedMarks);
        assertEquals(researchPublicationList1, allottedMarks);
        assertEquals(paperPresentedList1, allottedMarks);
        assertEquals(teacherAppointmentList1, allottedMarks);
        assertEquals(facultySeminarList, allottedMarks);
        assertEquals(courseList1, allottedMarks);
        assertEquals(admittedStudentList1, allottedMarks);
        assertEquals(123L, actualStudentCourseMapping.getId().longValue());
        assertSame(student2, actualStudentCourseMapping.getStudent());
    }
}

